config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do
    resources :doses do
    end
  end

  resources :cocktails
  resources :doses
  resources :ingredients

  root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :find_cocktail, only: [ :show, :edit, :update, :destroy ]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def edit

  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def find_cocktail
     @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_dose, only: [ :show, :edit, :update, :destroy ]

  def index
    @doses = Dose.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def edit

  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = @cocktail.doses.build(dose_params)
    # @dose = Dose.new(dose_params)
    # @dose.cocktail_id = @cocktail.id

    if @dose.save
      redirect_to @dose.cocktail
    else
       redirect_to @dose.cocktail
       # needs better solution
      # render 'new'
    end
  end

  def update
    @dose.update(dose_params)
    redirect_to doses_path
  end

  def destroy
    @dose.destroy
    redirect_to @dose.cocktail
  end

  private

  def find_dose
     @dose = Dose.find(params[:id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id )
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
   before_action :find_ingredient, only: [ :show, :edit, :update, :destroy ]

  def index
    @ingredients = Ingredient.all
  end

  def show
  end

  def new
    @ingredient = Ingredient.new
  end

  def edit

  end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to ingredients_path
    else
      render 'new'
    end
  end

  def update
    @ingredient.update(ingredient_params)
    redirect_to ingredients_path
  end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_path
  end

  private

  def find_ingredient
     @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_cocktail_dose_form.html.erb
<%= simple_form_for [@cocktail, Dose.new] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, collection: Ingredient.all %>
  <%= f.submit %>
<% end %>

app/views/cocktails/_cocktail_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>

<%= render 'cocktail_form' %>

app/views/cocktails/index.html.erb
<h1>Cocktails#index</h1>
<p>Find me in app/views/cocktails/index.html.erb</p>

<ul>
<% @cocktails.each do |cocktail| %>

  <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
<% end %>


</ul>
<%= link_to "New Cocktail", new_cocktail_path %>
<%= link_to "Ingredients", ingredients_path %>

app/views/cocktails/new.html.erb
<h1>Cocktails#new</h1>
<p>Find me in app/views/cocktails/new.html.erb</p>


<%= render 'cocktail_form' %>

app/views/cocktails/show.html.erb
<h1>Cocktails#show</h1>
<p>Find me in app/views/cocktails/show.html.erb</p>

<%= @cocktail.name %>
<ul>
  <% @cocktail.doses.each do |dose| %>
    <li><%= dose.description %> <%= dose.ingredient.name %>
      <%=link_to "Delete", dose_path(dose), method: :delete, data: {confirm:"Are you REALLY sure you want to delete it?"}  %>
    </li>
  <% end %>
</ul>

<%= render 'cocktail_dose_form' %>

<%= link_to "Edit", edit_cocktail_path %>
<%= link_to "Destroy", cocktail_path(@cocktail), method: :delete, data: {confirm:"Are you sure you want to delete it?"}%>

<%= link_to "home", cocktails_path %>

app/views/doses/_dose_form.html.erb
_dose_form.html.erb

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

<%= render 'dose_form' %>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

<ul>
<% @doses.each do |dose| %>

  <li><%= dose.cocktail.name %></li>
  <li><%= link_to dose.description, dose_path(dose) %></li>
  <li><%= dose.ingredient.name %></li>
<% end %>


</ul>
<%= link_to "New", new_dose_path %>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

<%= render 'dose_form' %>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

<%= @dose.description %>
<%= @dose.ingredient.name %>

<%= link_to "Edit", edit_dose_path %>
<%= link_to "Destroy", dose_path(@dose), method: :delete, data: {confirm:"Are you sure you want to delete it?"}%>

<%= link_to "home", doses_path %>

app/views/ingredients/_ingredient_form.html.erb
<%= simple_form_for @ingredient do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Ingredients#edit</h1>
<p>Find me in app/views/ingredients/edit.html.erb</p>

<%= render 'ingredient_form' %>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>
<p>Find me in app/views/ingredients/index.html.erb</p>

<ul>
<% @ingredients.each do |ingredient| %>

  <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
<% end %>


</ul>
<%= link_to "New", new_ingredient_path %>
<%= link_to "Home", cocktails_path %>

app/views/ingredients/new.html.erb
<h1>Ingredients#new</h1>
<p>Find me in app/views/ingredients/new.html.erb</p>

<%= render 'ingredient_form' %>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

<%= @ingredient.name %>

<%= link_to "Edit", edit_ingredient_path %>
<%= link_to "Destroy", ingredient_path(@ingredient), method: :delete, data: {confirm:"Are you sure you want to delete it?"}%>

<%= link_to "home", ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
 <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>